### ISSUE TITLE
Global distributed crontab

### ISSUE THREAD

**Issue by brainstorm** [fengsp/plan#1]
Brilliant module, congrats!

It would be extra awesome if it could be combined with, for instance, @ansible:

https://github.com/ansible/ansible

Often sysadmins have several machines running cron and they forget what is running on which, causing race conditions on services that rely on different states and dependencies.

Having both composable crontab modules *and* a global view of how crontabs look like across machines would be quite awesome feature.

Have you checked Chronos, for instance?:

http://airbnb.github.io/chronos/

**Comment by int3rlop3r** [comment]
@brainstorm Not sure if this is what you are looking for - 
https://github.com/int3rlop3r/crony 

It's still work in progress though! (:

**Comment by brainstorm** [comment]
Interesting, thanks for telling!
